Fix an issue where camera position isn't used in grid calculation
PacktPublishing/3D-Graphics-Rendering-Cookbook pull request #20
Opened 2022-12-28 10:18 UTC by disusdev

The camera position was missed from the grid calculation, so the grid always stuck in the origin.

2023-01-02 22:10 UTC, corporateshark commented
1) What does it change visually?

2) This changeset breaks Chapter 7.

2023-01-02 23:59 UTC, disusdev commented
Oh, I see, my fault, I forgot about an infinite plane. Here is the fix for that.
So the grid stays always in world origin, as we render the plane, but it is called an infinite grid, so I've added camera XZ position to plane and UV, to make sure that it will always draw the grid on camera XZ position.

**Before:**
![before_fix](https://user-images.githubusercontent.com/17259171/210285876-2bf8b46c-f237-4c6c-8563-4d625d63d8c2.gif)
**After:**
![after_fix](https://user-images.githubusercontent.com/17259171/210285892-a809d98d-87ec-42d4-a6e0-8f43aedefb8e.gif)

2023-01-03 04:35 UTC, corporateshark requested changes

2023-01-03 04:35 UTC, corporateshark commented on data/shaders/chapter07/VK03_InfinitePlane.vert
> +	cameraPos = vec2(iview[3][0], iview[3][2]);
Why not `-vec2(uvo.view[3][0], uvo.view[3][2])`?

2023-01-03 04:35 UTC, corporateshark commented on data/shaders/chapter07/VK03_InfinitePlane.vert
> +	position.x += cameraPos.x;
`position.xz += cameraPos.xy`;

2023-01-03 04:35 UTC, corporateshark commented on data/shaders/chapter05/GL01_grid.vert
> +	position.x += cameraPos.x;
`position.xz += cameraPos.xz;`

2023-01-05 03:56 UTC, disusdev commented on data/shaders/chapter07/VK03_InfinitePlane.vert
> +	cameraPos = vec2(iview[3][0], iview[3][2]);
Because we need camera position in world space, and I don't think that `-vec2(uvo.view[3][0], uvo.view[3][2])` can do the trick. But I could be wrong.

2023-01-05 04:42 UTC, corporateshark commented on data/shaders/chapter07/VK03_InfinitePlane.vert
> +	cameraPos = vec2(iview[3][0], iview[3][2]);
That should give the camera position in world space, yes. No need to invert this matrix as it is just a linear combination of a rotation and translation.

2023-01-07 11:06 UTC, disusdev commented on data/shaders/chapter07/VK03_InfinitePlane.vert
> +	cameraPos = vec2(iview[3][0], iview[3][2]);
hm... Isn't a linear combination more like a rotation around position? And in our case it is an fps camera, we did multiplication of rotation on translation, and we can no longer get a position without inverting the matrix.
![image](https://user-images.githubusercontent.com/17259171/211147049-ebbfa7f4-6348-419a-8cf8-eb90853d0e5c.png)

2023-01-08 20:49 UTC, corporateshark commented on data/shaders/chapter07/VK03_InfinitePlane.vert
> +	cameraPos = vec2(iview[3][0], iview[3][2]);
Ah, yes, you are right!

2023-01-08 20:52 UTC, merged

2023-01-08 20:53 UTC, corporateshark commented
Thank you for your contribution!