Fix endsWith()
PacktPublishing/3D-Graphics-Rendering-Cookbook pull request #30
Opened 2024-01-14 22:03 UTC by gcem

Current implementation of `endsWith` is wrong, since `strstr` finds the first match, not the last. To demonstrate:
```
endsWith("ba", "a"); // returns 1
endsWith("aa", "a"); // returns 0
```

This PR contains one possible fix, feel free to use something else.

Also, thanks for the awesome book!

2024-01-14 22:35 UTC, corporateshark requested changes

2024-01-14 22:35 UTC, corporateshark commented on shared/Utils.cpp
> +	const int sLength = strlen(s);
`size_t`

2024-01-14 22:47 UTC, gcem commented on shared/Utils.cpp
> +	const int sLength = strlen(s);
Done

2024-01-14 23:29 UTC, corporateshark requested changes

2024-01-14 23:29 UTC, corporateshark commented on shared/Utils.cpp
>  int endsWith(const char* s, const char* part)
Let's make it `bool`. It looks like `int` was a mistake here in the first place.

2024-01-14 23:29 UTC, corporateshark commented on shared/Utils.cpp
> +		return 0;
`return false;`

2024-01-14 23:29 UTC, corporateshark commented on shared/Utils.cpp
> +	return !strcmp(s + sLength - partLength, part);
`return strcmp(s + sLength - partLength, part) == 0;`

2024-01-15 04:03 UTC, merged

2024-01-15 04:03 UTC, corporateshark commented
@gcem Thank you for your contribution! 🙏